version: '3.9'
services:
  config-manager:
    container_name: config-manager
    build: 
      context: .
      dockerfile: dockerfile
      target: local
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis_cache
    env_file:
      - env/defaults.env
    ports:
      - '3000:3000'

  mongo:
    command: mongod --logpath /dev/null
    image: mongo
    container_name: mongo
    env_file:
      - env/docker.env
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  redis_cache:
    image: redis:7-alpine3.16
    container_name: redis_cache
    volumes: 
      - redis_cache_data:/data
    env_file:
      - env/docker.env
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --requirepass myRedisPass --loglevel warning

volumes:
  mongo_data:
  redis_cache_data:

networks:
  default:
    name: CONFIG_MANAGER_NETWORK