version: '3.9'
services:
  config-manager:
    container_name: config-manager
    build: 
      context: .
      dockerfile: dockerfile
      target: LOCAL
    volumes:
      - ./:/app
    depends_on:
      - mongo
    env_file:
      - env/defaults.env
    ports:
      - '3000:3000'

  mongo:
    command: mongod --logpath /dev/null
    image: mongo
    container_name: mongo
    env_file:
      - env/docker.env
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data:

networks:
  default:
    name: CONFIG_MANAGER_NETWORK