version: '3.9'
services:
  config-manager:
    container_name: config-manager
    build: 
      context: .
      dockerfile: dockerfile
      target: local
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - auth-manager
    env_file:
      - env/defaults.env
    ports:
      - '3000:3000'

  auth-manager:
    container_name: auth-manager
    image: cultify/auth-manager
    environment:
      - PORT=3001
      - PRINT_ENV=true
      - START_SWAGGER=true
      - AUTH_MANAGER_TOKEN_SECRET=super-secret
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis

  mongo:
    command: mongod --wiredTigerCacheSizeGB 1.5 --logpath /dev/null
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=configs
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --loglevel "warning"

volumes:
  mongo_data:

networks:
  default:
    name: CONFIG_MANAGER_NETWORK