version: "3.9"
services:
  web-client:
    container_name: web-client
    build:
      context: ./apps/web-client
      target: local
    depends_on:
      - web-api
    volumes:
      - ./apps/web-client:/app
      - ./node_modules:/app/node_modules
    environment:
      - ./apps/web-client/.env.development
    ports:
      - "5173:5173"

  web-api:
    container_name: web-api
    build:
      context: ./apps/web-api
      target: local
    volumes:
      - ./apps/web-api:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - mongo
      - redis
      - mosquitto
    env_file:
      - ./apps/web-api/env/.env
    ports:
      - 3001:3001

  mongo:
    command: mongod --quiet --wiredTigerCacheSizeGB 1.5 --logpath /dev/null
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=ACAP
    volumes:
      - mongo_acap_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass "redis" --logfile /dev/null

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_log:/mosquitto/log

volumes:
  mongo_acap_data:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:

networks:
  default:
    driver: bridge
    name: ACAP_NETWORK
