skip-missing: true
ignores:
  - '@storybook/addon-actions'
  - '@storybook/addon-essentials'
  - '@storybook/addon-interactions'
  - '@storybook/addon-links'
  - '@storybook/builder-vite'
  - '@storybook/preset-create-react-app'
  - '@storybook/testing-library'
  - '@chromatic-com/storybook'
  - '@storybook/addon-onboarding'
  - '@storybook/test'
  - '@testing-library/react'
  - '@testing-library/user-event'
  - '@types/react'
  - '@vitest/coverage-v8'
  - css-reset-and-normalize
  - dependency-cruiser
  - eslint-plugin-import
  - autoprefixer
  - postcss
  - prop-types
  - react-refresh
  - url
  - buffer
  - dotenv
  - eslint-plugin-prettier
  - eslint-plugin-storybook
  - eslint-plugin-unused-imports
  - husky
