appConfig:
  port: 3003
  address: 0.0.0.0
  printEnv: false
  startSwagger: false
  nodeEnv: local
  bodyLimit: 104857600
  brcsChannel: 'CHAT_BRCS'

bullMQConfig:
  connection:
    port: 6379
    host: keydb
    password: redis
    username: default

redisPubSubConfig:
    port: 6379
    host: keydb
    password: redis
    username: default
    connectionName: CHATHUB
