appConfig:
  port: 3002
  address: 0.0.0.0
  printEnv: false
  startSwagger: false
  nodeEnv: local
  bodyLimit: 104857600
  brokers:
    useRedisPubSub: false
    useBullMQ: false
    useMQTT: false
    useKafka: false
    useRabbitMQ: false

redisPubSubConfig:
  options:
    port: 6379
    host: keydb
    password: redis
    username: default

bullMQConfig:
  connection:
    port: 6379
    host: keydb
    password: redis
    username: default

kafkaClientConfig:
  options:
    client:
      ssl: false
      clientId: acap
      brokers: 
        - kafka:9092
      retry:
        retries: 12
        initialRetryTime: 300000
        factor: 1
        multiplier: 1
        maxRetryTime: 3600000

rabbitMQClientConfig:
  options:
    urls: amqp://rabbitmq:rabbitmq@rabbitmq:5672

mqttClientConfig:
  brokerUrl: null
  options:
    port: 1883
    keepalive: 5000
    connectTimeout: 5000
    reconnectPeriod: 1000
    resubscribe: true
    protocol: mqtt
    hostname: mosquitto
    username: null
    password: null
