appConfig:
  port: 3001
  address: 0.0.0.0
  printEnv: false
  startSwagger: false
  nodeEnv: "local"
  bodyLimit: "104857600"
  crypto:
    secret: CryptoShield2024
  realm:
    ttl: 300
    resolveEnv: false
    namespacePostfix: ACAP
    gzipThreshold: 20
  brokers:
    useBullMQ: false

mongoConfig:
  uri: mongodb://mongo:27017
  ssl: false
  tlsAllowInvalidCertificates: false
  dbName: ACAP
  user: mongo
  pass: mongo

minioConfig:
  endPoint: "minio"
  port: 9000
  useSSL: false
  accessKey: "minio"
  secretKey: "minio2024"
  bucket: "acap"

redisConfig:
  host: keydb
  port: 6379
  ttl: 600
  max: 100
  db: 0
  password: redis
  username: default

bullMQConfig:
  connection:
    port: 6379
    host: keydb
    password: redis
    username: default
