version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      target: local
    depends_on:
      - acap
    volumes:
      - ./:/app
    environment:
      - .env.development
    ports:
      - '5173:5173'

  acap:
    container_name: acap
    image: ehildt/acap
    environment:
      - START_SWAGGER=true
      - PRINT_ENV=false
      - REALM_NAMESPACE_POSTFIX=acap
      - REALM_TTL=360 
      - REALM_GZIP_THRESHOLD=20
    depends_on:
      - mongo
      - redis
      - mosquitto
    ports:
      - '3001:3001'

  mongo:
    command: mongod --quiet --wiredTigerCacheSizeGB 1.5 --logpath /dev/null
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=ACAP
    volumes:
      - mongo_acap_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass "redis" --logfile /dev/null
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_log:/mosquitto/log

volumes:
  mongo_acap_data:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:

networks:
  default:
    name: ACAP_NETWORK
