appConfig:
  port: 3002
  address: 0.0.0.0
  printEnv: true
  startSwagger: true
  nodeEnv: "local"
  bodyLimit: "104857600"
  brokers:
    useRedisPubSub: true
    useBullMQ: true
    useMQTT: true

redisPubSubConfig:
  options:
    port: 6379
    host: redis
    password: redis
    username: default

bullMQConfig:
  connection:
    port: 6379
    host: redis
    password: redis
    username: default

mqttClientConfig:
  brokerUrl: null
  options:
    port: 1883
    keepalive: 5000
    connectTimeout: 5000
    reconnectPeriod: 1000
    resubscribe: true
    protocol: "mqtt"
    hostname: mosquitto
    username: null
    password: null
