appConfig:
  port: 3001
  address: 0.0.0.0
  printEnv: true
  startSwagger: true
  nodeEnv: 'local'
  services: 
    useRedisPubSub: false
    useBullMQ: false
    useMQTT: true

realmConfig:
  ttl: 300
  resolveEnv: false
  namespacePostfix: DSCA
  gzipThreshold: 20

mongoConfig:
  uri: mongodb://mongo:27017
  ssl: false
  tlsAllowInvalidCertificates: true
  dbName: DSCD
  user: mongo
  pass: mongo

redisConfig:
  host: redis
  port: 6379
  ttl: 600
  max: 100
  db: 0
  password: redis
  username: default

redisPubSubConfig: 
  options:
    port: 6379
    host: redis
    password: redis
    username: default

bullMQConfig:
  connection:
    port: 6379
    host: redis
    password: redis
    username: default