skip-missing: true
ignores: 
  - "@nestjs/schematics"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - "@types/jest"
  - "@types/prettier"
  - "conventional-changelog-conventionalcommits"
  - "dependency-cruiser"
  - "jest-junit"
  - "source-map-support"
  - "ts-jest"
  - "ts-loader"
  - "tsconfig-paths"