#!/bin/sh
. "$(dirname "$0")/prepare.sh"

check_working_directory
check_branch_identifier

# makes sure all dependencies are up to date
info 'npm run ncu:validate' && npm run ncu:validate

# dry run tests
info 'npm run test:clearCache' && npm run test:clearCache
info 'npm run test -- --silent' && npm run test -- --silent

# no unused exports
info 'npm run ts-unused-exports' && npm run ts-unused-exports

# add known orphans to .dependency-orphans.json
info 'npm run dependency-cruiser' && npm run dependency-cruiser
