name: MAIN CI/CD NodeJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '18'
          - '20'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install NestJS CLI
        run: npm i -g @nestjs/cli

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:cov -- --coverageThreshold=none

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint Code
        run: npm run lint

      - name: Analyze Dependencies
        run: npm run depcruiser

      - name: Check Unused Exports
        run: npm run ts-unused-exports

      - name: Check Licenses
        run: npm run licensee

      - name: Build (if present)
        run: npm run build --if-present

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Back-Merge into DEV
        run: |
          git fetch
          git checkout dev origin/dev
          git merge --no-ff origin/main
          if [[ $? -eq 0 ]]; then
            git push origin dev
          fi
