name: MAIN_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  STORE_PATH:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Getting pnpm store
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Mounting pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Unit & Coverage Tests
        run: |
          prpm run -r test
          prpm run -r test:cov

      - name: Upload Coverage Reports To Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint Code
        run: prpm run -r lint

      - name: Check Unused Dependencies
        run: prpm run -r depcruiser

      - name: Check Unused Exports
        run: prpm run -r ts-unused-exports

      - name: Build Check
        run: prpm run -r build:prod

      - name: Semantic Release
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
