name: Node.js CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 20
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache dependencies                                                                                      
      uses: actions/cache@v3                                                                                        
      with:                                                                                                         
        path: ~/.npm                                                                                                
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm install -g @nestjs/cli
    - run: npm ci --omit=dev --ignore-scripts
    - run: npm test
    - run: npm run lint
    - run: npm run depcruiser
    - run: npm run ts-unused-exports
    - run: npm run licensee
    - run: npm run build:prod --if-present