name: ON_PUSH

on:
  push:
    branches:
      - "*"

env:
  STORE_PATH:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Getting pnpm store
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Mounting pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Unit & Coverage Tests
        run: |
          lerna run test
          lerna run test:cov

      - name: Upload Coverage Reports To Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint Code
        run: lerna run lint

      - name: Check Unused Dependencies
        run: lerna run depcruiser

      - name: Check Unused Exports
        run: lerna run ts-unused-exports

      - name: Build Check
        run: lerna run build
